---
name: 'Cleanup Environment'
description: 'Cleans up Go cache and module directories'
runs:
  using: "composite"
  steps:
    - name: Cleanup on Linux/Mac
      if: runner.os != 'Windows'
      run: |
        ls -la ~/go/pkg/mod || echo "Directory does not exist"
        chmod -R 0755 ~/go/pkg/mod ~/.cache/go-build ~/.cache/golangci-lint ~/.cache/buf || true
        rm -rf ~/.cache/go-build ~/go/pkg/mod || true
      shell: bash

    - name: Cleanup on Windows
      if: runner.os == 'Windows'
      run: |
        if (Test-Path -Path "$env:USERPROFILE\go\pkg\mod") {
          Get-ChildItem -Force -Recurse "$env:USERPROFILE\go\pkg\mod"
        } else {
          Write-Output "Directory does not exist"
        }
        if (Test-Path -Path "$env:USERPROFILE\.cache\go-build") {
          Remove-Item -Recurse -Force "$env:USERPROFILE\.cache\go-build"
        }
        if (Test-Path -Path "$env:USERPROFILE\go\pkg\mod") {
          Remove-Item -Recurse -Force "$env:USERPROFILE\go\pkg\mod"
        }
      shell: pwsh
